In [1]:
import pandas as pd

In [3]:
df = pd.read_pickle('/mnt/SYNO/macrohet_syno/results/dfs/dt_df.pkl')

In [4]:
df

,index,Acquisition ID,Biological Replicate,Cell ID,Compound,Concentration,Eccentricity,Experiment ID,Final Infection Status,Frame,...,Unique ID,dMphi Area (µm),dMtb Area (µm),dt,r2,x,y,doubling_times,dmtb_values,Strain/Compound
0,0,"(3, 4)",1,426,CTRL,EC0,0.929721,PS0000,0.0,0.0,...,426.3.4,-92.746118,-0.424621,7.0,0.944356,457.172943,8.791715,"[2.0, 3.0, 4.0, 9.0, 17.0]","[0.15, 0.31, 0.62, 1.23, 2.46]",RD1
1,1,"(3, 4)",1,426,CTRL,EC0,0.977788,PS0000,0.0,1.0,...,426.3.4,-92.746118,-0.424621,7.0,0.944356,459.138947,6.718642,"[2.0, 3.0, 4.0, 9.0, 17.0]","[0.15, 0.31, 0.62, 1.23, 2.46]",RD1
2,2,"(3, 4)",1,426,CTRL,EC0,0.733415,PS0000,0.0,2.0,...,426.3.4,-92.746118,-0.424621,7.0,0.944356,460.555237,10.785886,"[2.0, 3.0, 4.0, 9.0, 17.0]","[0.15, 0.31, 0.62, 1.23, 2.46]",RD1
3,3,"(3, 4)",1,426,CTRL,EC0,0.685354,PS0000,0.0,3.0,...,426.3.4,-92.746118,-0.424621,7.0,0.944356,455.878815,11.143067,"[2.0, 3.0, 4.0, 9.0, 17.0]","[0.15, 0.31, 0.62, 1.23, 2.46]",RD1
4,4,"(3, 4)",1,426,CTRL,EC0,0.727210,PS0000,0.0,4.0,...,426.3.4,-92.746118,-0.424621,7.0,0.944356,462.634186,14.050420,"[2.0, 3.0, 4.0, 9.0, 17.0]","[0.15, 0.31, 0.62, 1.23, 2.46]",RD1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1315004,1797106,"(6, 12)",3,1874,BDQ,EC99,0.571813,ND0003,1.0,NaN,...,1874.6.12,55.088959,1.095075,NaN,NaN,227.093262,130.358139,[],[],RD1
1315005,1797107,"(6, 12)",3,1874,BDQ,EC99,0.373264,ND0003,1.0,NaN,...,1874.6.12,55.088959,1.095075,NaN,NaN,226.622925,130.532120,[],[],RD1
1315006,1797108,"(6, 12)",3,1874,BDQ,EC99,0.490623,ND0003,1.0,NaN,...,1874.6.12,55.088959,1.095075,NaN,NaN,225.366608,129.932709,[],[],RD1
1315007,1797109,"(6, 12)",3,1874,BDQ,EC99,0.693277,ND0003,1.0,NaN,...,1874.6.12,55.088959,1.095075,NaN,NaN,226.424683,128.489410,[],[],RD1
1315008,1797110,"(6, 12)",3,1874,BDQ,EC99,0.752570,ND0003,1.0,NaN,...,1874.6.12,55.088959,1.095075,NaN,NaN,225.741119,126.533669,[],[],RD1

In [17]:
positions = df[['Compound', 'Concentration', 'Experiment ID', 'Acquisition ID', 'Strain']].drop_duplicates()

In [20]:
positions.groupby(['Compound', 'Concentration', 'Strain']).size().reset_index(name='Counts')

   Compound Concentration Strain  Counts
0       BDQ          EC50    RD1       4
1       BDQ          EC50     WT       6
2       BDQ          EC99    RD1       4
3       BDQ          EC99     WT       6
4      CTRL           EC0    RD1      11
5      CTRL           EC0    UNI       4
6      CTRL           EC0     WT      12
7       INH          EC50    RD1       4
8       INH          EC50     WT       6
9       INH          EC99    RD1       4
10      INH          EC99     WT       6
11      PZA          EC50    RD1       4
12      PZA          EC50     WT       6
13      PZA          EC99    RD1       4
14      PZA          EC99     WT       6
15      RIF          EC50    RD1       4
16      RIF          EC50     WT       6
17      RIF          EC99    RD1       4
18      RIF          EC99     WT       6

In [19]:
positions.groupby(['Compound', 'Concentration', 'Strain']).size().reset_index(name='Counts').sort_values(by=['Strain', 'Concentration', 'Compound'])

   Compound Concentration Strain  Counts
4      CTRL           EC0    RD1      11
0       BDQ          EC50    RD1       4
7       INH          EC50    RD1       4
11      PZA          EC50    RD1       4
15      RIF          EC50    RD1       4
2       BDQ          EC99    RD1       4
9       INH          EC99    RD1       4
13      PZA          EC99    RD1       4
17      RIF          EC99    RD1       4
5      CTRL           EC0    UNI       4
6      CTRL           EC0     WT      12
1       BDQ          EC50     WT       6
8       INH          EC50     WT       6
12      PZA          EC50     WT       6
16      RIF          EC50     WT       6
3       BDQ          EC99     WT       6
10      INH          EC99     WT       6
14      PZA          EC99     WT       6
18      RIF          EC99     WT       6